### ISSUE TITLE
Cannot run more than one task with is action

### ISSUE THREAD

**Issue by yooniks9** [dawidd6/action-ansible-playbook#13]
after first action is finished, the ansible_key has been cleanup, when start 2nd action, it has this error

`@github-actionsgithub-actions
/ build
.github#L1
ENOENT: no such file or directory, unlink '.ansible_key'`

**Comment by dawidd6** [comment]
Could you please provide a link to the failed workflow run?

**Comment by yooniks9** [comment]
it's a private repo


here is my Workflow:

`name: Continue Integration

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repo
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Create .env file for composer
      run: |
        cp .env.example .env
    - name: Composer install
      uses: docker://composer:2.0.2
      with:
        args: install --prefer-dist --no-interaction --no-suggest

    - name: Setup Nodejs 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: "[Nodejs] npm install & npm run production"
      run: |
        npm install
        npm run production
    - name: Begin - Set permission to github-runner
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible-begin.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [webservers]
          ${{secrets.SSH_SERVER}}
          [webservers:vars]
          ansible_python_interpreter=/usr/bin/python3
          ansible_user=${{secrets.SSH_USER}}
          ansible_sudo_pass=${{secrets.SSH_USER_PASS}}
        vault_password: ${{secrets.SSH_USER_PASS}}
        options: |
          -vvvv
          --user="${{secrets.SSH_USER}}"
          --extra-vars "ansible_sudo_pass=${{secrets.SSH_USER_PASS}}"
    - name: Deploy to server without git & .env
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      with:
        flags: '-avz --exclude=".git*" --exclude .env'
        options: ''
        ssh_options: '-p ${{secrets.SSH_PORT}}'
        src: '.'
        dest: '${{secrets.SSH_USER}}@${{secrets.SSH_SERVER}}:/var/www/redat/'

    - name: End - Set permission to www-data, clear laravel cache
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible-final.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [webservers]
          ${{secrets.SSH_SERVER}}
          [webservers:vars]
          ansible_python_interpreter=/usr/bin/python3
          ansible_user=${{secrets.SSH_USER}}
          ansible_sudo_pass=${{secrets.SSH_USER_PASS}}
        vault_password: ${{secrets.SSH_USER_PASS}}
        options: |
          -vvvv
          --user="${{secrets.SSH_USER}}"
          --extra-vars "ansible_sudo_pass=${{secrets.SSH_USER_PASS}}"`

**Comment by yooniks9** [comment]
it will fail if i run 2 actions uses: dawidd6/action-ansible-playbook@v2

If i remove either one of them, It's working without any problem

https://share.yooniks.dev/file/dsupload/Screen-Shot-2020-12-06-at-8.25.43-PM.png

**Comment by yooniks9** [comment]
Thank you, It's working
