### ISSUE TITLE
sshpass program missing

### ISSUE THREAD

**Issue by yooniks9** [dawidd6/action-ansible-playbook#17]
Hello, Please check the container, is it installed sshpass?
  
  
  [webservers:vars]
  ansible_user=***
  ansible_sudo_pass=***
  ansible_ssh_pass=***
  
/usr/bin/ansible-playbook ansible-begin.yml --inventory-file .ansible_inventory

PLAY [webservers] **************************************************************

TASK [Set permission to ***] *****************************************
fatal: [***]: FAILED! => {"msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"}

**Comment by dawidd6** [comment]
This Action runs directly on the runner, not in container. If you are missing some program, install it on your own.

**Comment by yooniks9** [comment]
I removed ansible_ssh_pass from vars, 
and use
`key: ${{secrets.SSH_PRIVATE_KEY}}`
it works like a charm
