### ISSUE TITLE
`sudo: ansible-playbook: command not found`

### ISSUE THREAD

**Issue by m-roberts** [dawidd6/action-ansible-playbook#27]
Without `sudo`, the command resolves to`/opt/pipx_bin/ansible-playbook ...`. With `sudo`, we get `/usr/bin/sudo ansible-playbook ...`, which results in the error.

I'm guessing that its losing the PATH - Perhaps `sudo --preserve-env` would fix this?

Running in a GitHub Action workflow directly, this is also the case. I have to run `sudo $(which ansible-playbook)` to resolve the command path currently.

**Comment by dawidd6** [comment]
Please submit a PR for this. Even better if you include a test for it in workflows.
