### ISSUE TITLE
Optionally Forced Colors

### ISSUE THREAD

**Issue by bswinnerton** [dawidd6/action-ansible-playbook#31]
Hi there,

What's the rationale behind forcing colors in the terminal here:

https://github.com/dawidd6/action-ansible-playbook/blob/fbcc2c2baeb2fb55d38e624f73e2685b8ca23e22/main.js#L82

Would you be open to a change that optionally allows forcing the color (and defaults to true for backwards compatibility)? Alternatively, could this line be removed altogether?

My use case is this: I'm running this Action and taking the output of the run and adding it as an issue comment. Unfortunately right now, no matter what is set in `ansible.cfg` for `nocolor`, the ANSI color escape sequences are always present. Ideally these could be conditionally turned off.

**Comment by dawidd6** [comment]
Please submit a PR adding additional `color` or `no_color` input.
