### ISSUE TITLE
msg: 'Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host'

### ISSUE THREAD

**Issue by ticktockhouse** [dawidd6/action-ansible-playbook#59]
I am getting this message when I attempt to do an ansible run against any hosts for a hosted runner:

```
fatal: [chubb-dev-web]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host'
  unreachable: true
```

As far as I can see, there is no output from `sshd` at `DEBUG` level.

Here is the SSH key setup, using a jumpbox (which may be causing the issue: not sure): https://gist.github.com/ticktockhouse/81629e9c97817a2a0cd741dc4293abda

As you can see, the "known_hosts" values are stored in secrets, gleaned using `ssh-keyscan`. Of course, it's possible that this may have been stored incorrectly, would be good to know if I have got this correct.

Many thanks in advance!

**Comment by clincha** [comment]
This doesn't look like you have an issue with this action, it looks like you have an issue with your SSH key configuration. In the code you shared you don't even call the action that @dawidd6 made. 

If I were you I'd look into the keys you're using and the sshd configuration (/etc/ssh/sshd_config) on the host you're trying to connect to.

**Comment by ticktockhouse** [comment]
@clincha Thanks for your reply. You're right, I didn't share the whole of the github action- I've edited the gist to include this.

The other weird thing is, as you can see in the updated action, I do a manual ssh to the box in question and I can report that this works fine.

Here is more context around the error arisiing in Ansible:

```
<jumpbox_ip> ESTABLISH SSH CONNECTION FOR USER: None
<jumpbox_ip> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/runner/work/flawless-infra/flawless-infra/ansible/chubb/.ansible_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=.ansible_known_hosts -J <server_ip> -o 'ControlPath="/home/runner/.ansible/cp/9a9d293357"' <jumpbox_ip> '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<jumpbox_ip> (255, b'', b'kex_exchange_identification: Connection closed by remote host\r\n')
fatal: [chubb-staging-web]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host'
  unreachable: true

```

**Comment by clincha** [comment]
Can you cut out everything except for the ansible step and check if that works? Also remove the known hosts stuff please (try to get the minimum working then build from there).

> 'IdentityFile="/home/runner/work/flawless-infra/flawless-infra/ansible/chubb/.ansible_key"'

It seems to be passing in the key correctly. Can you please post your ansible.cfg file or however you pass in your Ansible environment. 

I still get the feeling that this isn't an issue with this action but an issue with the key or the server itself

**Comment by dawidd6** [comment]
No response. Closing.
