### ISSUE TITLE
Problem in post phase

### ISSUE THREAD

**Issue by siren** [dawidd6/action-ansible-playbook#6]
I am seeing this error on my build @github:

```
'Post job cleanup.
==> Deleting ".ansible_key" file
##[error]ENOENT: no such file or directory, unlink '.ansible_key'
```
The ansible playbook executes succesfully, but every action ends up in failed state because of the problem in post phase.

I have a configuration that specifies a directory, perhaps it is relevant

**Comment by dawidd6** [comment]
Thanks for reporting. Should be fixed now. I'll create a new release and retag v2.

**Comment by siren** [comment]
Great, thanks. It's working now.
