### ISSUE TITLE
Deprecation of "save-state" and "set-output"

### ISSUE THREAD

**Issue by ttunua** [dawidd6/action-ansible-playbook#60]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by dawidd6** [comment]
Could submit a PR for that?

**Comment by ttunua** [comment]
I could if I have time in the future.

I just don't have time at the moment to become familiar with what is needed since the change is significant.
Looks like a bunch of remapping that would be simpler for the author/builder.

"**Action authors** who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

**Action and workflow authors** who are using save-state or set-output via stdout should update to use the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)."

**Comment by dawidd6** [comment]
Done and released.
