### ISSUE TITLE
Feature request: ansible-galaxy install force flag

### ISSUE THREAD

**Issue by clincha** [dawidd6/action-ansible-playbook#64]
>/bin/ansible-galaxy role install -r galaxy-requirements.yml
>monolithprojects.github_actions_runner (1.16.0) is already installed, skipping.
>/bin/ansible-galaxy collection install -r galaxy-requirements.yml
>Process install dependency map
>ERROR! Cannot meet requirement community.general:5.8.0 as it is already installed at version '5.6.0'. Use --force to overwrite
>Error: The process '/bin/ansible-galaxy' failed with exit code 1

When trying to install an updated version of an Ansible Galaxy package there is an error message, The error suggests setting the force flag to overwrite the previous version of the package. It's not possible to pass through this force flag using the module at this time.

**Comment by dawidd6** [comment]
Please open a PR adding this.

**Comment by dawidd6** [comment]
No interest since then. Closing.
