### ISSUE TITLE
Missing playbook

### ISSUE THREAD

**Issue by dkasyan** [dawidd6/action-ansible-playbook#70]
##
Hi! Nice play. Just can't find my playbook? Did you know why? I tried manually adding paths and boosting file permissions. My efforts were for nothing. Please help!
######
Run dawidd6/action-ansible-playbook@v2
  with:
    playbook: playbook.yaml
    key: ***
    inventory: [all]
  example.com
  
  [group1]
  example.com
  
    known_hosts: .known_hosts
    options: --inventory inventory
  --limit all
  
/opt/pipx_bin/ansible-playbook playbook.yaml --inventory inventory --limit all --key-file .ansible_key --inventory-file .ansible_inventory --ssh-common-args=-o UserKnownHostsFile=.ansible_known_hosts
ERROR! the playbook: playbook.yaml could not be found
Error: The process '/opt/pipx_bin/ansible-playbook' failed with exit code 1

**Comment by cupen** [comment]
So, where is your playbook.yml? ;p

**Comment by MasteringBOX** [comment]
I can't fine mine either. It is supposed to be in the repository as I understand, but it doesn't seem to work.

**Comment by dawidd6** [comment]
Show me your workflows first. How should I know what are you really doing.

**Comment by MasteringBOX** [comment]
Thanks for replying @dawidd6  
My workflow 
`name: Deploy
on:
  # Triggers this Action on push or pull request events on the "main" branch and when manually requested from the "Actions" tab
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  deploy_code:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: ansible/deploy.yml # path to your Ansible playbook
          key: ${{ secrets.ansible_private_key }} # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
          inventory: ${{ secrets.ansible_inventory }} # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets
`

The error I get
`dawidd[6](https://github.com/MasteringBOX/Kampi-React/actions/runs/4265742822/jobs/7425432959#step:2:7)/action-ansible-playbook@v2.6.1
/opt/pipx_bin/ansible-playbook ansible/deploy.yml --inventory-file .ansible_inventory
ERROR! the playbook: ansible/deploy.yml could not be found`

I tried different paths, and changed the playbook directory with the directory variable. I have the ansible playbook and roles in ansible directory in my repository. I'm I supposed to have them somewhere else?

**Comment by dawidd6** [comment]
You need to check the repository first. Use `actions/checkout`.

**Comment by MasteringBOX** [comment]
Ups, for some reason I though I didn't need that when using your action. Thanks, solved.
