### ISSUE TITLE
Ensure SSH private key uses LF and not CRLF

### ISSUE THREAD

**Issue by AntoineFr** [dawidd6/action-ansible-playbook#72]
When using this GitHub action, I encountered an error saying `Load key ".../.ansible_key": error in libcrypto`.
After trying to reproduce the bug, I found that it's because my SSH key ends with CRLF (created on Windows) instead of LF (as on Linux).

- `echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ansible_key` doesn't work
- `echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > .ansible_key` works

I tried different ways to paste the SSH key in a secret but it always resulted in a key with wrong line endings.
I suggest you remove the `\r` characters in the code that copies the key to a file

**Comment by dawidd6** [comment]
I mean, if you are using the action on Linux runner and supply Ansible with a CRLF formatted private key file no wonder it refuses to work. Don't think it's an issue with the action nor Ansible. Just provide the key with correct formatting.

**Comment by jjpaulo2** [comment]
@AntoineFr could you share the workflow that you got it fixed with that line?

**Comment by AntoineFr** [comment]
> @AntoineFr could you share the workflow that you got it fixed with that line?

Hello @jjpaulo2, it was something like this

```
      - name: Fix SSH key bug
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > .ansible_key
          chmod 400 .ansible_key

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory inventories/production/hosts
            --check
            --diff
            --key-file .ansible_key
```
but I have changed that since so I don't have the full working code anymore

**Comment by jjpaulo2** [comment]
Thanks for share it @AntoineFr ❤️
