### ISSUE TITLE
How to pass multiple extra variables?

### ISSUE THREAD

**Issue by boranliu** [dawidd6/action-ansible-playbook#76]
Trying to pass multiple variables to `--extra-vars` without using a json file, but it looks like I am getting the following error:
`ansible-playbook: error: unrecognized arguments: `

Trying to separate the arguments by space it doesnt seem to be working.
``` 
options: |
            --verbose
            --inventory ${{ vars.ANSIBLE_HOSTS_FILE_PATH }}
            --extra-vars a=something b=somethingelse
```

**Comment by tp199314** [comment]
Hi @boranliu I ran into the same error. How did you solve this error? Thank you in advance.
