### ISSUE TITLE
Node16 deprecated

### ISSUE THREAD

**Issue by baumerdev** [dawidd6/action-ansible-playbook#89]
I'm getting warnings in my Github Actions:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dawidd6/action-ansible-playbook@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Seems it is time for another version bump.

**Comment by WiegerWolf** [comment]
@dawidd6 could you please tag a release of this? `v2.8.0` or something?

**Comment by dawidd6** [comment]
Released. Enjoy.
